export function getGridRows() {
  return [
    { type: 'header', label: 'OPERATIONS', section: 'ops' },
    { type: 'input', label: 'Sales Plan %', id: 'general.salesRate', format: 'number', section: 'ops' },
    { type: 'output', label: 'Total Sold (Units)', id: 'totalUnitsSold', format: 'number', section: 'ops' },
    { type: 'input', label: 'Prod A Qty', id: 'qty.A', format: 'number', section: 'ops' },
    { type: 'input', label: 'Prod A Price', id: 'price.A', format: 'currency', section: 'ops' },
    { type: 'input', label: 'Prod B Qty', id: 'qty.B', format: 'number', section: 'ops' },
    { type: 'input', label: 'Prod B Price', id: 'price.B', format: 'currency', section: 'ops' },
    { type: 'input', label: 'Prod C Qty', id: 'qty.C', format: 'number', section: 'ops' },
    { type: 'input', label: 'Prod C Price', id: 'price.C', format: 'currency', section: 'ops' },
    { type: 'header', label: 'CAPACITY & UTILIZATION', section: 'cap' },
    { type: 'displayLimit', label: 'Machine Limit (Hrs)', id: 'machine', section: 'cap' },
    { type: 'status', label: 'Machine Usage', id: 'machine', section: 'cap' },
    { type: 'displayLimit', label: 'Labour Limit (Hrs)', id: 'labour', section: 'cap' },
    { type: 'status', label: 'Labour Usage', id: 'labour', section: 'cap' },
    { type: 'header', label: 'GROWTH (CAPEX & EXPENSE)', section: 'growth' },
    { type: 'input', label: 'Machine Inv ($)', id: 'inv.machine', format: 'currency', section: 'growth' },
    { type: 'input', label: 'Labour Inv ($)', id: 'inv.labour', format: 'currency', section: 'growth' },
    { type: 'header', label: 'FINANCE', section: 'fin' },
    { type: 'input', label: 'New ST Debt (+)', id: 'finance.newST', format: 'currency', section: 'fin' },
    { type: 'input', label: 'New LT Debt (+)', id: 'finance.newLT', format: 'currency', section: 'fin' },
    { type: 'input', label: 'Pay ST Princ (-)', id: 'finance.payST', format: 'currency', section: 'fin' },
    { type: 'input', label: 'Pay LT Princ (-)', id: 'finance.payLT', format: 'currency', section: 'fin' },
    { type: 'input', label: 'Dividends (-)', id: 'finance.div', format: 'currency', section: 'fin' },
    { type: 'header', label: 'INCOME STATEMENT', section: 'inc' },
    { type: 'output', label: 'Revenue', id: 'revenue', format: 'currency', section: 'inc' },
    { type: 'output', label: 'COGS (Var)', id: 'varCost', format: 'currency', negative: true, section: 'inc' },
    { type: 'output', label: 'Gross Profit', id: 'grossProfit', format: 'currency', highlight: true, section: 'inc' },
    { type: 'spacer', label: '', section: 'inc' },
    { type: 'output', label: 'Depreciation', id: 'depreciation', format: 'currency', negative: true, section: 'inc' },
    { type: 'output', label: 'Training & Dev', id: 'trainingExp', format: 'currency', negative: true, section: 'inc' },
    { type: 'output', label: 'EBIT', id: 'ebit', format: 'currency', section: 'inc' },
    { type: 'output', label: 'Interest', id: 'interest', format: 'currency', negative: true, section: 'inc' },
    { type: 'output', label: 'Taxes', id: 'tax', format: 'currency', negative: true, section: 'inc' },
    { type: 'output', label: 'Net Income', id: 'netIncome', format: 'currency', highlight: true, section: 'inc' },
    { type: 'header', label: 'METRICS', section: 'met' },
    { type: 'output', label: 'ROE %', id: 'roe', format: 'percent', highlight: true, section: 'met' },
    { type: 'output', label: 'ROA %', id: 'roa', format: 'percent', section: 'met' },
    { type: 'output', label: 'Asset Turnover', id: 'assetTurnover', format: 'decimal', section: 'met' },
    { type: 'output', label: 'Equity Multiplier', id: 'equityMultiplier', format: 'decimal', section: 'met' },
    { type: 'output', label: 'Debt/Equity', id: 'debtEquityRatio', format: 'decimal', section: 'met' },
    { type: 'header', label: 'FINANCIAL POSITION', section: 'pos' },
    { type: 'output', label: 'Cash', id: 'cash', format: 'currency', checkNegative: true, section: 'pos' },
    { type: 'output', label: 'Inventory (Units)', id: 'inventoryUnits', format: 'number', section: 'pos' },
    { type: 'output', label: 'Inventory ($)', id: 'inventory', format: 'currency', section: 'pos' },
    { type: 'output', label: 'Fixed Assets', id: 'fixedAssets', format: 'currency', section: 'pos' },
    { type: 'output', label: 'Total Assets', id: 'totalAssets', format: 'currency', highlight: true, section: 'pos' },
    { type: 'spacer', label: '', section: 'pos' },
    { type: 'output', label: 'ST Debt', id: 'stDebt', format: 'currency', section: 'pos' },
    { type: 'output', label: 'LT Debt', id: 'ltDebt', format: 'currency', section: 'pos' },
    { type: 'output', label: 'Equity', id: 'equity', format: 'currency', section: 'pos' },
    { type: 'output', label: 'Total Liab. & Equity', id: 'totalLiabEquity', format: 'currency', highlight: true, section: 'pos' },
  ];
}
